services:
  db:
    image: bitnami/postgresql:17.4.0
    platform: linux/amd64
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - docker-fastapi-base

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@db:5432/${POSTGRESQL_DATABASE}
      - BACKEND_CORS_ORIGINS=["http://localhost:3000"]
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - docker-fastapi-base

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - docker-fastapi-base

volumes:
  db-data:


networks:
  docker-fastapi-base:
    driver: bridge
