[project]
name = "backend"
version = "0.1.0"
description = "Backend for flex living assessment"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.17.2",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.128.0",
    "psycopg[binary]>=3.3.2",
    "pyjwt>=2.10.1",
    "sqlalchemy>=2.0.45",
]
